### ISSUE TITLE
Scripts are not working

### ISSUE THREAD

**Issue by fahrunnaseem** [eliasnogueira/appium-parallel-execution#15]
Hi Elias,

With the code as your reference, I have automated the application from my organization. I was able to start the application on my android and IOS device. But the scripts are not continued before the test is getting stopped. Want to know if there is any change required to continue further. It would be very helpful for your response. Feel free to ping me in my mail id : fahrunnazim
@gmail.com

Regards,
Naseem

**Comment by eliasnogueira** [comment]
Hi @fahrunnaseem 
Have you tried to run this project itself before adopting it?
If yes and you found no issue, I would say it could be a problem during your implementation.

Anyway, it's always good to add the exceptions you are getting. :)

**Comment by fahrunnaseem** [comment]
Hi,

Thanks for responding back.

I have tried your script as well it was working fine.
I don't think I have done any implementation changes to your script. Other
than the test steps.

Attached below is the framework. Let me know if there is any change
required. Take your time.
It's always good to get feedback from the author.

 appium-parallel-execution-master.zip
<https://drive.google.com/file/d/1mN8z-UNti4gg6T3n30S0teKKQekqubgT/view?usp=drive_web>

**Comment by eliasnogueira** [comment]
Hey @fahrunnaseem 
Can you send me the exception... I can help you better in this way than evaluate what you did because, unfortunately, I won't have much time right now.

**Comment by fahrunnaseem** [comment]
Find below the exception.
[image: Screenshot 2022-05-17 at 6.36.32 PM.png]

**Comment by eliasnogueira** [comment]
@fahrunnaseem there's no screenshot :( 
Can you send the log (copy-paste it from the failing point)?

**Comment by fahrunnaseem** [comment]
Elias,

Below is the exception

java.lang.NullPointerException: Cannot invoke
"io.appium.java_client.MobileElement.click()" because
"this.heartfulnesstrainer" is null
at
com.parallel.page_object.MainScreenPage.clickheartfulnesstrainer(MainScreenPage.java:70)
at com.parallel.Heartsapp.Loginscreen(Heartsapp.java:16)
at
java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at
org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at
org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by eliasnogueira** [comment]
It seems that your method `clickheartfulnesstrainer` in the `MainScreenPage` class has a null reference.
I would advise you to review what you have implemented, as it is not related to this repo.

**Comment by fahrunnaseem** [comment]
Elais,

Thanks for the update..
