### ISSUE TITLE
How to ensure the Test Data  loaded for each test using Data provider is threadsafe using this approach

### ISSUE THREAD

**Issue by araveeti** [eliasnogueira/appium-parallel-execution#2]
Case : Once I implement the Data provider to read data from external files.Can we ensure the thread safe using this approach.

Now that the tests are running in parallel. What are the advantages/dis advantages of we run the Methods in parallel?

I am very much curions to get some information... :)

**Comment by araveeti** [comment]
Hi,

Can we have a look at the above query plz?

**Comment by eliasnogueira** [comment]
You must implement the data using a thread-safe approach like implementing a ThreadLocal approach for the driver and making sure your data will be placed on the same thread.
